### PR TITLE
invoking singleton constructor of Configurator

### PR DESCRIPTION
**Pull request by gansai**
After making singleton constructor of Configurator, updated Main class

### CODE REVIEW

**Comment by oskopek** [comment]
Hello @gansai! Thank you for your contribution. Next time, please submit one PR instead of two, if both commits refer to a single specific issue. You see, the automatic build on PR #14 failed to even compile, just because it references the "old" version of the `Main` class.

I will merge both of the PRs in one go and make a code style change on top (don't let that discourage you!). Thank you again for your contribution!

**Comment by oskopek** [comment]
Also, @gansai, if you want, add yourself to `AUTHORS.adoc`  and submit a PR!

**Comment by gansai** [comment]
Thanks @oskopek for the opportunity to contribute to Open Source.
Yes, next time, I shall submit one PR instead of multiple.

**Comment by oskopek** [comment]
Thank you for your time and effort! I merged your `AUTHORS.adoc` PR.

**Comment by gansai** [comment]
Welcome. Your work is wonderful and thanks for opportunity to contribute.

**Pull request merged**
